import "./globals.css";
import Navbar from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import AuthProvider from "./(components)/AuthProvider";
import ReactProvider from "@/components/ReactProvider";

export const metadata = {
  title: "GYM",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="site-wrapper">
        <ReactProvider>
          <AuthProvider>
            <Navbar />

            <div>{children}</div>
          </AuthProvider>
          <Footer />
        </ReactProvider>
      </body>
    </html>
  );
}
