export const Cardio = [
  { id: 1, src: "/cardio/cardio1.jpg" },
  { id: 2, src: "/cardio/cardio2.jpg" },
  { id: 3, src: "/cardio/cardio3.jpg" },
  { id: 4, src: "/cardio/cardio4.jpg" },
  { id: 5, src: "/cardio/cardio5.jpg" },
  { id: 6, src: "/cardio/cardio6.jpg" },
  { id: 7, src: "/cardio/cardio7.jpg" },
  { id: 8, src: "/cardio/cardio8.jpg" },
  { id: 9, src: "/cardio/cardio9.jpg" },
  { id: 10, src: "/cardio/cardio10.jpg" },
  { id: 11, src: "/cardio/cardio11.jpg" },
  { id: 12, src: "/cardio/cardio12.jpg" },
  { id: 13, src: "/cardio/cardio13.jpg" },
  { id: 14, src: "/cardio/cardio14.jpg" },
  { id: 15, src: "/cardio/cardio15.jpg" },
  { id: 16, src: "/cardio/cardio16.jpg" },
  { id: 17, src: "/cardio/cardio17.jpg" },
];
